"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import NovaSidebar from "@/components/NovaSidebar";

type Modus = "uebersicht" | "bedarfe" | "vorschlaege" | "termine";
type Artikel = { id: number; artikelnummer: string; produktname: string; groesse?: string; variante?: string; verfuegbar: number; mindestbestand: number; bestellt: number; inAuftrag: number; einheit?: string };
type Vorschlag = { id: number; vorgeschlageneMenge: number; begruendung: string; status: string; erstelltAm: string; artikel: Artikel };
type Termin = { id: number; auftragsnummer: string; kunde: string; status: string; prioritaet: string; liefertermin?: string; ueberfaellig: boolean; positionen: Array<{ menge: number; artikel: Artikel }> };
type Daten = { bedarfe: Artikel[]; vorschlaege: Vorschlag[]; termine: Termin[]; offeneBestellungen: number };
const TITEL: Record<Modus, [string, string]> = { uebersicht: ["Disposition", "Bedarfe, Engpässe und Termine vorausschauend steuern"], bedarfe: ["Bedarfsübersicht", "Artikel unter Mindestbestand und ungedeckte Bedarfe"], vorschlaege: ["Beschaffungsvorschläge", "Automatisch ermittelte Vorschläge prüfen und freigeben"], termine: ["Terminüberwachung", "Fällige und überfällige Kundenaufträge kontrollieren"] };

export default function DispositionModul({ modus }: { modus: Modus }) {
  const [daten, setDaten] = useState<Daten | null>(null); const [fehler, setFehler] = useState(""); const [sendet, setSendet] = useState(false); const [suche, setSuche] = useState("");
  const laden = useCallback(async () => { try { const r = await fetch("/api/disposition", { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.fehler); setDaten(d); setFehler(""); } catch (e) { setFehler(e instanceof Error ? e.message : "Disposition konnte nicht geladen werden."); } }, []);
  useEffect(() => { void laden(); }, [laden]);
  async function senden(aktion: string, inhalt: object = {}) { setSendet(true); try { const r = await fetch("/api/disposition", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ aktion, ...inhalt }) }); const d = await r.json(); if (!r.ok) throw new Error(d.fehler); await laden(); } catch (e) { setFehler(e instanceof Error ? e.message : "Vorgang fehlgeschlagen."); } finally { setSendet(false); } }
  const bedarfe = useMemo(() => daten?.bedarfe.filter((a) => `${a.artikelnummer} ${a.produktname} ${a.variante ?? ""}`.toLowerCase().includes(suche.toLowerCase())) ?? [], [daten, suche]);
  const vorschlaege = useMemo(() => daten?.vorschlaege.filter((v) => `${v.artikel.artikelnummer} ${v.artikel.produktname} ${v.status}`.toLowerCase().includes(suche.toLowerCase())) ?? [], [daten, suche]);
  const ueberfaellig = daten?.termine.filter((t) => t.ueberfaellig).length ?? 0; const offeneVorschlaege = daten?.vorschlaege.filter((v) => v.status === "NEU").length ?? 0; const [titel, untertitel] = TITEL[modus];
  return <main className="min-h-screen bg-[var(--nova-hintergrund)] text-[var(--nova-text)]"><NovaSidebar /><section className="ml-20 px-8 py-8"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[var(--nova-akzent)]">Planung & Steuerung</p><h1 className="mt-2 text-4xl font-bold">{titel}</h1><p className="mt-2 text-[var(--nova-text-schwaecher)]">{untertitel}</p></div>{(modus === "uebersicht" || modus === "vorschlaege") && <button disabled={sendet} onClick={() => void senden("vorschlaege-erzeugen")} className="rounded-xl bg-[var(--nova-akzent)] px-5 py-3 font-semibold text-white disabled:opacity-50">{sendet ? "Wird berechnet..." : "Vorschläge aktualisieren"}</button>}</div>{fehler && <p className="mt-6 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-300">{fehler}</p>}
  {daten && modus === "uebersicht" && <><div className="mt-8 grid gap-4 md:grid-cols-4"><Karte titel="Kritische Bedarfe" wert={daten.bedarfe.length} farbe="text-red-400" /><Karte titel="Neue Vorschläge" wert={offeneVorschlaege} farbe="text-amber-400" /><Karte titel="Überfällige Termine" wert={ueberfaellig} farbe="text-red-400" /><Karte titel="Offene Bestellungen" wert={daten.offeneBestellungen} farbe="text-sky-400" /></div><Abschnitt titel="Dringendste Bedarfe"><BedarfsTabelle artikel={daten.bedarfe.slice(0, 10)} /></Abschnitt></>}
  {daten && modus === "bedarfe" && <><Suche wert={suche} setzen={setSuche} /><Abschnitt titel={`${bedarfe.length} kritische Artikel`}><BedarfsTabelle artikel={bedarfe} /></Abschnitt></>}
  {daten && modus === "vorschlaege" && <><Suche wert={suche} setzen={setSuche} /><Abschnitt titel={`${vorschlaege.length} Beschaffungsvorschläge`}><div className="divide-y divide-[var(--nova-rand)]">{vorschlaege.map((v) => <div key={v.id} className="grid items-center gap-3 px-5 py-4 lg:grid-cols-[1.5fr_0.8fr_1.5fr_0.8fr_auto]"><span><b>{v.artikel.artikelnummer}</b><small className="block text-[var(--nova-text-schwaecher)]">{v.artikel.produktname}</small></span><b className="text-[var(--nova-akzent)]">{v.vorgeschlageneMenge.toLocaleString("de-DE")} {v.artikel.einheit}</b><span className="text-sm text-[var(--nova-text-schwaecher)]">{v.begruendung}</span><span>{v.status}</span>{v.status === "NEU" ? <div className="flex gap-2"><button onClick={() => void senden("vorschlag-status", { id: v.id, status: "FREIGEGEBEN" })} className="rounded-lg bg-emerald-500/15 px-3 py-2 text-xs text-emerald-300">Freigeben</button><button onClick={() => void senden("vorschlag-status", { id: v.id, status: "ABGELEHNT" })} className="rounded-lg bg-red-500/15 px-3 py-2 text-xs text-red-300">Ablehnen</button></div> : <span />}</div>)}</div></Abschnitt></>}
  {daten && modus === "termine" && <Abschnitt titel={`${daten.termine.length} überwachte Aufträge`}><div className="divide-y divide-[var(--nova-rand)]">{daten.termine.map((t) => <div key={t.id} className={`grid gap-3 px-5 py-4 md:grid-cols-4 ${t.ueberfaellig ? "bg-red-500/5" : ""}`}><b className="text-[var(--nova-akzent)]">{t.auftragsnummer}</b><span>{t.kunde}</span><span>{t.liefertermin ? new Date(t.liefertermin).toLocaleDateString("de-DE") : "–"}</span><span className={t.ueberfaellig ? "font-semibold text-red-400" : "text-emerald-400"}>{t.ueberfaellig ? "Überfällig" : t.status}</span></div>)}{daten.termine.length === 0 && <Leer text="Keine terminierten offenen Aufträge." />}</div></Abschnitt>}
  {!daten && !fehler && <p className="mt-8">Dispositionsdaten werden geladen...</p>}</div></section></main>;
}
function Karte({ titel, wert, farbe }: { titel: string; wert: number; farbe: string }) { return <div className="rounded-2xl border border-[var(--nova-rand)] bg-[var(--nova-flaeche)] p-6"><p className="text-sm text-[var(--nova-text-schwaecher)]">{titel}</p><p className={`mt-3 text-3xl font-bold ${farbe}`}>{wert.toLocaleString("de-DE")}</p></div>; }
function Abschnitt({ titel, children }: { titel: string; children: React.ReactNode }) { return <section className="mt-8 overflow-hidden rounded-2xl border border-[var(--nova-rand)] bg-[var(--nova-flaeche)]"><h2 className="border-b border-[var(--nova-rand)] px-5 py-4 text-xl font-semibold">{titel}</h2>{children}</section>; }
function Suche({ wert, setzen }: { wert: string; setzen: (v: string) => void }) { return <input value={wert} onChange={(e) => setzen(e.target.value)} placeholder="Artikelnummer oder Produkt suchen..." className="mt-8 w-full max-w-md rounded-xl border border-[var(--nova-rand)] bg-[var(--nova-flaeche)] px-4 py-3 outline-none focus:border-[var(--nova-akzent)]" />; }
function BedarfsTabelle({ artikel }: { artikel: Artikel[] }) { return <div className="divide-y divide-[var(--nova-rand)]">{artikel.map((a) => <div key={a.id} className="grid gap-3 px-5 py-4 md:grid-cols-[1.5fr_repeat(4,0.7fr)]"><span><b>{a.artikelnummer}</b><small className="block text-[var(--nova-text-schwaecher)]">{a.produktname}{a.variante ? ` · ${a.variante}` : ""}</small></span><Zahl label="Verfügbar" wert={a.verfuegbar} rot={a.verfuegbar < a.mindestbestand} /><Zahl label="Mindestbestand" wert={a.mindestbestand} /><Zahl label="Bestellt" wert={a.bestellt} /><Zahl label="In Auftrag" wert={a.inAuftrag} /></div>)}{artikel.length === 0 && <Leer text="Keine kritischen Bedarfe vorhanden." />}</div>; }
function Zahl({ label, wert, rot }: { label: string; wert: number; rot?: boolean }) { return <span className={rot ? "font-semibold text-red-400" : ""}><small className="block text-[var(--nova-text-schwaecher)]">{label}</small>{wert.toLocaleString("de-DE")}</span>; }
function Leer({ text }: { text: string }) { return <p className="p-8 text-center text-[var(--nova-text-schwaecher)]">{text}</p>; }
