"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import NovaSidebar from "@/components/NovaSidebar";

type Modus = "uebersicht" | "kunden" | "angebote";
type Kunde = { id: number; kundennummer: string; firmenname: string; ansprechpartner?: string; email?: string; telefon?: string; ort?: string; aktiv: boolean };
type Angebot = { id: number; angebotsnummer: string; titel: string; status: string; nettowert: number; gueltigBis?: string; kunde: Kunde };
type Daten = { kunden: Kunde[]; angebote: Angebot[] };

const TEXTE: Record<Modus, [string, string]> = { uebersicht: ["Vertrieb", "Kunden, Angebote und Verkaufschancen im Überblick"], kunden: ["Kunden", "Kundenstammdaten und Ansprechpartner verwalten"], angebote: ["Angebote", "Angebote erstellen und ihren Status verfolgen"] };

export default function VertriebModul({ modus }: { modus: Modus }) {
  const [daten, setDaten] = useState<Daten | null>(null); const [fehler, setFehler] = useState(""); const [sendet, setSendet] = useState(false); const [suche, setSuche] = useState("");
  const [kunde, setKunde] = useState({ firmenname: "", ansprechpartner: "", email: "", telefon: "", ort: "" });
  const [angebot, setAngebot] = useState({ kundeId: "", titel: "", nettowert: "", gueltigBis: "" });
  const laden = useCallback(async () => { try { const r = await fetch("/api/vertrieb", { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.fehler); setDaten(d); setFehler(""); } catch (e) { setFehler(e instanceof Error ? e.message : "Vertrieb konnte nicht geladen werden."); } }, []);
  useEffect(() => { void laden(); }, [laden]);
  async function senden(aktion: string, inhalt: object) { setSendet(true); try { const r = await fetch("/api/vertrieb", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ aktion, ...inhalt }) }); const d = await r.json(); if (!r.ok) throw new Error(d.fehler); await laden(); return true; } catch (e) { setFehler(e instanceof Error ? e.message : "Speichern fehlgeschlagen."); return false; } finally { setSendet(false); } }
  async function kundeSpeichern(e: FormEvent) { e.preventDefault(); if (await senden("kunde-anlegen", kunde)) setKunde({ firmenname: "", ansprechpartner: "", email: "", telefon: "", ort: "" }); }
  async function angebotSpeichern(e: FormEvent) { e.preventDefault(); if (await senden("angebot-anlegen", angebot)) setAngebot({ kundeId: "", titel: "", nettowert: "", gueltigBis: "" }); }
  const kunden = useMemo(() => daten?.kunden.filter((k) => `${k.kundennummer} ${k.firmenname} ${k.ansprechpartner ?? ""}`.toLowerCase().includes(suche.toLowerCase())) ?? [], [daten, suche]);
  const angebote = useMemo(() => daten?.angebote.filter((a) => `${a.angebotsnummer} ${a.titel} ${a.kunde.firmenname}`.toLowerCase().includes(suche.toLowerCase())) ?? [], [daten, suche]);
  const pipeline = daten?.angebote.filter((a) => ["ENTWURF", "VERSENDET"].includes(a.status)).reduce((s, a) => s + a.nettowert, 0) ?? 0;
  const [titel, untertitel] = TEXTE[modus];

  return <main className="min-h-screen bg-[var(--nova-hintergrund)] text-[var(--nova-text)]"><NovaSidebar /><section className="ml-20 px-8 py-8"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold uppercase tracking-[0.2em] text-[var(--nova-akzent)]">Kunden & Verkauf</p><h1 className="mt-2 text-4xl font-bold">{titel}</h1><p className="mt-2 text-[var(--nova-text-schwaecher)]">{untertitel}</p>{fehler && <p className="mt-6 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-red-300">{fehler}</p>}
  {daten && modus === "uebersicht" && <><div className="mt-8 grid gap-4 md:grid-cols-3"><Karte text="Aktive Kunden" wert={daten.kunden.filter((k) => k.aktiv).length.toLocaleString("de-DE")} /><Karte text="Offene Angebote" wert={daten.angebote.filter((a) => ["ENTWURF", "VERSENDET"].includes(a.status)).length.toLocaleString("de-DE")} /><Karte text="Vertriebspipeline" wert={pipeline.toLocaleString("de-DE", { style: "currency", currency: "EUR" })} /></div><Tabelle titel="Letzte Angebote"><Angebote angebote={daten.angebote.slice(0, 8)} onStatus={(id, status) => void senden("angebot-status", { id, status })} /></Tabelle></>}
  {daten && modus === "kunden" && <><Form titel="Neuen Kunden anlegen"><form onSubmit={kundeSpeichern} className="grid gap-4 md:grid-cols-3"><Feld label="Firmenname *" wert={kunde.firmenname} setzen={(v) => setKunde({ ...kunde, firmenname: v })} /><Feld label="Ansprechpartner" wert={kunde.ansprechpartner} setzen={(v) => setKunde({ ...kunde, ansprechpartner: v })} /><Feld label="Ort" wert={kunde.ort} setzen={(v) => setKunde({ ...kunde, ort: v })} /><Feld label="E-Mail" typ="email" wert={kunde.email} setzen={(v) => setKunde({ ...kunde, email: v })} /><Feld label="Telefon" wert={kunde.telefon} setzen={(v) => setKunde({ ...kunde, telefon: v })} /><Button sendet={sendet} text="Kunde speichern" /></form></Form><Suche wert={suche} setzen={setSuche} text="Kunde suchen..." /><Tabelle titel={`${kunden.length} Kunden`}><div className="divide-y divide-[var(--nova-rand)]">{kunden.map((k) => <div key={k.id} className="grid gap-2 px-5 py-4 md:grid-cols-4"><b className="text-[var(--nova-akzent)]">{k.kundennummer}</b><span>{k.firmenname}</span><span>{k.ansprechpartner || "–"}</span><span className="text-[var(--nova-text-schwaecher)]">{k.ort || "–"}</span></div>)}</div></Tabelle></>}
  {daten && modus === "angebote" && <><Form titel="Neues Angebot"><form onSubmit={angebotSpeichern} className="grid gap-4 md:grid-cols-4"><label className="text-sm"><span className="mb-2 block text-[var(--nova-text-schwaecher)]">Kunde *</span><select required value={angebot.kundeId} onChange={(e) => setAngebot({ ...angebot, kundeId: e.target.value })} className="w-full rounded-xl border border-[var(--nova-rand)] bg-[var(--nova-hintergrund)] px-4 py-3"><option value="">Auswählen</option>{daten.kunden.map((k) => <option key={k.id} value={k.id}>{k.firmenname}</option>)}</select></label><Feld label="Titel *" wert={angebot.titel} setzen={(v) => setAngebot({ ...angebot, titel: v })} /><Feld label="Nettowert" typ="number" wert={angebot.nettowert} setzen={(v) => setAngebot({ ...angebot, nettowert: v })} /><Feld label="Gültig bis" typ="date" wert={angebot.gueltigBis} setzen={(v) => setAngebot({ ...angebot, gueltigBis: v })} /><Button sendet={sendet} text="Angebot erstellen" /></form></Form><Suche wert={suche} setzen={setSuche} text="Angebot oder Kunde suchen..." /><Tabelle titel={`${angebote.length} Angebote`}><Angebote angebote={angebote} onStatus={(id, status) => void senden("angebot-status", { id, status })} /></Tabelle></>}
  {!daten && !fehler && <p className="mt-8">Vertriebsdaten werden geladen...</p>}</div></section></main>;
}

function Karte({ text, wert }: { text: string; wert: string }) { return <div className="rounded-2xl border border-[var(--nova-rand)] bg-[var(--nova-flaeche)] p-6"><p className="text-sm text-[var(--nova-text-schwaecher)]">{text}</p><p className="mt-3 text-3xl font-bold">{wert}</p></div>; }
function Form({ titel, children }: { titel: string; children: React.ReactNode }) { return <section className="mt-8 rounded-2xl border border-[var(--nova-rand)] bg-[var(--nova-flaeche)] p-6"><h2 className="mb-5 text-xl font-semibold">{titel}</h2>{children}</section>; }
function Tabelle({ titel, children }: { titel: string; children: React.ReactNode }) { return <section className="mt-6 overflow-hidden rounded-2xl border border-[var(--nova-rand)] bg-[var(--nova-flaeche)]"><h2 className="border-b border-[var(--nova-rand)] px-5 py-4 text-xl font-semibold">{titel}</h2>{children}</section>; }
function Suche({ wert, setzen, text }: { wert: string; setzen: (v: string) => void; text: string }) { return <input value={wert} onChange={(e) => setzen(e.target.value)} placeholder={text} className="mt-6 w-full max-w-md rounded-xl border border-[var(--nova-rand)] bg-[var(--nova-flaeche)] px-4 py-3 outline-none focus:border-[var(--nova-akzent)]" />; }
function Feld({ label, wert, setzen, typ = "text" }: { label: string; wert: string; setzen: (v: string) => void; typ?: string }) { return <label className="text-sm"><span className="mb-2 block text-[var(--nova-text-schwaecher)]">{label}</span><input required={label.includes("*")} type={typ} value={wert} onChange={(e) => setzen(e.target.value)} className="w-full rounded-xl border border-[var(--nova-rand)] bg-[var(--nova-hintergrund)] px-4 py-3 outline-none focus:border-[var(--nova-akzent)]" /></label>; }
function Button({ sendet, text }: { sendet: boolean; text: string }) { return <button disabled={sendet} className="self-end rounded-xl bg-[var(--nova-akzent)] px-5 py-3 font-semibold text-white disabled:opacity-50">{sendet ? "Speichert..." : text}</button>; }
function Angebote({ angebote, onStatus }: { angebote: Angebot[]; onStatus: (id: number, status: string) => void }) { return <div className="divide-y divide-[var(--nova-rand)]">{angebote.map((a) => <div key={a.id} className="grid items-center gap-3 px-5 py-4 md:grid-cols-[1fr_1.5fr_1fr_1fr_auto]"><b className="text-[var(--nova-akzent)]">{a.angebotsnummer}</b><span>{a.kunde.firmenname}<small className="block text-[var(--nova-text-schwaecher)]">{a.titel}</small></span><span>{a.nettowert.toLocaleString("de-DE", { style: "currency", currency: "EUR" })}</span><span>{a.status}</span><select value={a.status} onChange={(e) => onStatus(a.id, e.target.value)} className="rounded-lg border border-[var(--nova-rand)] bg-[var(--nova-hintergrund)] px-3 py-2 text-xs"><option>ENTWURF</option><option>VERSENDET</option><option>ANGENOMMEN</option><option>ABGELEHNT</option></select></div>)}{angebote.length === 0 && <p className="p-8 text-center text-[var(--nova-text-schwaecher)]">Noch keine Angebote vorhanden.</p>}</div>; }
