"use client";
import { useCallback,useEffect,useState } from "react";
import { BatteryCharging,MapPin,RefreshCw,ScanLine,Signal,Wifi,WifiOff } from "lucide-react";

type Scanner={id:string;geraet:string;status:"ONLINE"|"OFFLINE";mitarbeiter:string;personalnummer:string;akku:number;wlan:number;letzteBuchung:string;buchung:string;lagerplatz:string};
type Daten={scanner:Scanner[];aktualisiertAm:string;intervallSekunden:number};
export default function MdeLive(){const[daten,setDaten]=useState<Daten|null>(null),[fehler,setFehler]=useState(""),[laedt,setLaedt]=useState(false);const laden=useCallback(async()=>{setLaedt(true);try{const r=await fetch(`/api/lager/mde-live?t=${Date.now()}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j.fehler);setDaten(j);setFehler("")}catch(e){setFehler(e instanceof Error?e.message:"MDE-Status konnte nicht geladen werden.")}finally{setLaedt(false)}},[]);useEffect(()=>{void laden();const timer=setInterval(()=>void laden(),10000);return()=>clearInterval(timer)},[laden]);const online=daten?.scanner.filter(s=>s.status==="ONLINE").length??0;
return <main className="min-h-screen bg-[var(--nova-hintergrund)] p-8 pl-28 text-[var(--nova-text)]"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.24em] text-[var(--nova-akzent)]">Lager · Echtzeit</p><h1 className="mt-1 flex items-center gap-3 text-4xl font-bold"><ScanLine/>Live MDE Übersicht</h1><p className="mt-2 text-[var(--nova-text-schwaecher)]">Alle mobilen Scanner, Mitarbeiter und Lageraktivitäten auf einen Blick.</p></div><button onClick={()=>void laden()} className="flex items-center gap-2 rounded-xl bg-[var(--nova-akzent)] px-5 py-3 font-bold text-white hover:brightness-110"><RefreshCw size={18} className={laedt?"animate-spin":""}/>Live aktualisieren</button></div>{fehler&&<p className="mt-6 rounded-xl bg-red-500/10 p-4 text-red-300">{fehler}</p>}{daten&&<><div className="mt-8 grid gap-4 sm:grid-cols-3"><K t="Scanner gesamt" w={daten.scanner.length} farbe="text-[var(--nova-text)]"/><K t="Online" w={online} farbe="text-emerald-400"/><K t="Offline" w={daten.scanner.length-online} farbe="text-red-400"/></div><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{daten.scanner.map(s=><article key={s.id} className={`rounded-2xl border bg-[var(--nova-flaeche)] p-5 ${s.status==="ONLINE"?"border-emerald-500/40":"border-red-500/30 opacity-75"}`}><div className="flex justify-between gap-3"><div><h2 className="text-lg font-bold">{s.id}</h2><p className="text-sm text-[var(--nova-text-schwaecher)]">{s.geraet}</p></div><span className={`flex h-fit items-center gap-2 rounded-full px-3 py-1 text-xs font-bold ${s.status==="ONLINE"?"bg-emerald-500/15 text-emerald-400":"bg-red-500/15 text-red-400"}`}>{s.status==="ONLINE"?<Wifi size={14}/>:<WifiOff size={14}/>} {s.status}</span></div><div className="mt-5 border-y border-[var(--nova-rand)] py-4"><b>{s.mitarbeiter}</b><p className="text-xs text-[var(--nova-text-schwaecher)]">Personalnummer {s.personalnummer}</p></div><div className="mt-4 grid grid-cols-2 gap-3"><Info icon={BatteryCharging} t="Akku" w={`${s.akku} %`} warn={s.akku<30}/><Info icon={Signal} t="WLAN" w={`${s.wlan} %`} warn={s.wlan<40}/><Info icon={MapPin} t="Lagerplatz" w={s.lagerplatz}/><Info icon={RefreshCw} t="Letzte Buchung" w={new Date(s.letzteBuchung).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}/></div><p className="mt-4 truncate rounded-xl bg-[var(--nova-hintergrund)] p-3 text-sm">{s.buchung}</p></article>)}</div><p className="mt-5 text-right text-xs text-[var(--nova-text-schwaecher)]">Stand {new Date(daten.aktualisiertAm).toLocaleTimeString("de-DE")} · automatische Aktualisierung alle {daten.intervallSekunden} Sekunden</p></>}</div></main>}
function K({t,w,farbe}:{t:string;w:number;farbe:string}){return <div className="rounded-2xl border border-[var(--nova-rand)] bg-[var(--nova-flaeche)] p-5"><p className="text-sm text-[var(--nova-text-schwaecher)]">{t}</p><b className={`mt-2 block text-3xl ${farbe}`}>{w}</b></div>};function Info({icon:Icon,t,w,warn=false}:{icon:typeof Wifi;t:string;w:string;warn?:boolean}){return <div className="rounded-xl bg-[var(--nova-hintergrund)] p-3"><span className="flex items-center gap-2 text-xs text-[var(--nova-text-schwaecher)]"><Icon size={14}/>{t}</span><b className={`mt-1 block truncate text-sm ${warn?"text-amber-400":""}`}>{w}</b></div>}
