import type { SpracheRegion } from "@/lib/theme";

type Woerterbuch = Record<string, string>;

const EN: Woerterbuch = {
  Unternehmen:"Company", Prozesse:"Processes", Zusammenarbeit:"Collaboration", Administration:"Administration", Einstellungen:"Settings", Abmelden:"Sign out", "Feierabend / NOVA schließen":"Finish work / Close NOVA", "NOVA durchsuchen …":"Search NOVA …",
  Zentrale:"Central office", Vertrieb:"Sales", Disposition:"Planning", Buchhaltung:"Accounting", "CAD-Büro":"CAD office", Einkauf:"Purchasing", Lager:"Warehouse", Konfektion:"Finishing", Logistik:"Logistics", Kommunikation:"Communication", Organisation:"Organization", Mitarbeiter:"Employees", Benutzerverwaltung:"User management", Integrationen:"Integrations", Sicherheit:"Security", Alarmcenter:"Alert center",
  Übersicht:"Overview", Telefonzentrale:"Switchboard", Abwesenheiten:"Absences", Stempeluhr:"Time clock", Kunden:"Customers", Angebote:"Quotations", Bedarfe:"Requirements", Beschaffungsvorschläge:"Procurement proposals", Terminüberwachung:"Schedule monitoring", Rechnungen:"Invoices", Zahlungseingänge:"Incoming payments", Dokumente:"Documents", Freigaben:"Approvals", Bestellungen:"Orders", Lieferanten:"Suppliers", Bestand:"Inventory", Lagerplätze:"Storage locations", "MDE-Erfassung":"Mobile data capture", "PC-Bestätigung":"PC confirmation", Umlagerungen:"Transfers", Inventur:"Stocktaking", "Barcode / MDE":"Barcode / MDE", Qualitätsprüfung:"Quality inspection", Prüfaufträge:"Inspection orders", Sperrbestand:"Blocked stock", Konfektionsaufträge:"Finishing orders", Aufträge:"Orders", Kommissionierung:"Picking", Ladungen:"Loads", Versand:"Shipping", Lieferscheine:"Delivery notes", "Interner Chat":"Internal chat", "Team-Kommunikation":"Team communication", Dateien:"Files", "Audio & Video":"Audio & video", Systemmeldungen:"System notifications", "Automatischer Versand":"Automatic dispatch", Unternehmenskalender:"Company calendar", "Persönlicher Kalender":"Personal calendar", Terminplanung:"Scheduling", Besprechungen:"Meetings", Urlaubsplanung:"Leave planning", Ressourcenplanung:"Resource planning", Aufgabenverwaltung:"Task management", Schichtplanung:"Shift planning", "Digitale Arbeitsaufträge":"Digital work orders", "Interne Nachrichten":"Internal messages", Aktivitätsprotokolle:"Activity logs", Benutzer:"Users", Rollen:"Roles", Rechte:"Permissions", Systemeinstellungen:"System settings", Protokolle:"Logs", Performance:"Performance",
  Speichern:"Save", Senden:"Send", Antworten:"Reply", Abbrechen:"Cancel", Löschen:"Delete", Bearbeiten:"Edit", Suchen:"Search", Aktualisieren:"Refresh", Zurück:"Back", Weiter:"Next", Schließen:"Close", Aktiv:"Active", Inaktiv:"Inactive", Offen:"Open", Abgeschlossen:"Completed", Storniert:"Cancelled", Gesamt:"Total", Status:"Status", Datum:"Date", Name:"Name", Beschreibung:"Description", Menge:"Quantity", Artikel:"Item", Artikelnummer:"Item number", Lieferant:"Supplier", Bestellung:"Order", "Keine Daten vorhanden":"No data available", "Wird geladen...":"Loading...", "Daten konnten nicht geladen werden.":"Data could not be loaded."
};

const ES: Woerterbuch = { ...EN, Unternehmen:"Empresa",Prozesse:"Procesos",Zusammenarbeit:"Colaboración",Einstellungen:"Configuración",Abmelden:"Cerrar sesión","Feierabend / NOVA schließen":"Finalizar jornada / Cerrar NOVA","NOVA durchsuchen …":"Buscar en NOVA …",Zentrale:"Central",Vertrieb:"Ventas",Disposition:"Planificación",Buchhaltung:"Contabilidad","CAD-Büro":"Oficina CAD",Einkauf:"Compras",Lager:"Almacén",Konfektion:"Confección",Logistik:"Logística",Kommunikation:"Comunicación",Organisation:"Organización",Mitarbeiter:"Empleados",Benutzerverwaltung:"Gestión de usuarios",Integrationen:"Integraciones",Sicherheit:"Seguridad",Alarmcenter:"Centro de alertas",Übersicht:"Resumen",Kunden:"Clientes",Angebote:"Ofertas",Bestellungen:"Pedidos",Lieferanten:"Proveedores",Bestand:"Inventario",Lagerplätze:"Ubicaciones",Umlagerungen:"Traslados",Inventur:"Inventario físico",Qualitätsprüfung:"Control de calidad",Prüfaufträge:"Órdenes de inspección",Freigaben:"Aprobaciones",Sperrbestand:"Stock bloqueado",Aufträge:"Órdenes",Kommissionierung:"Preparación",Ladungen:"Cargas",Versand:"Envío",Lieferscheine:"Albaranes",Dokumente:"Documentos",Dateien:"Archivos",Besprechungen:"Reuniones",Urlaubsplanung:"Planificación de vacaciones",Speichern:"Guardar",Senden:"Enviar",Antworten:"Responder",Abbrechen:"Cancelar",Löschen:"Eliminar",Bearbeiten:"Editar",Suchen:"Buscar",Aktualisieren:"Actualizar",Zurück:"Atrás",Weiter:"Siguiente",Schließen:"Cerrar",Offen:"Abierto",Abgeschlossen:"Completado",Storniert:"Cancelado",Gesamt:"Total",Datum:"Fecha",Beschreibung:"Descripción",Menge:"Cantidad",Artikel:"Artículo",Artikelnummer:"Número de artículo",Lieferant:"Proveedor",Bestellung:"Pedido","Keine Daten vorhanden":"No hay datos disponibles","Wird geladen...":"Cargando..." };

const TR: Woerterbuch = { ...EN, Unternehmen:"Şirket",Prozesse:"Süreçler",Zusammenarbeit:"İş birliği",Einstellungen:"Ayarlar",Abmelden:"Çıkış yap","Feierabend / NOVA schließen":"Mesaiyi bitir / NOVA'yı kapat","NOVA durchsuchen …":"NOVA'da ara …",Zentrale:"Merkez",Vertrieb:"Satış",Disposition:"Planlama",Buchhaltung:"Muhasebe","CAD-Büro":"CAD ofisi",Einkauf:"Satın alma",Lager:"Depo",Konfektion:"Konfeksiyon",Logistik:"Lojistik",Kommunikation:"İletişim",Organisation:"Organizasyon",Mitarbeiter:"Çalışanlar",Benutzerverwaltung:"Kullanıcı yönetimi",Integrationen:"Entegrasyonlar",Sicherheit:"Güvenlik",Alarmcenter:"Alarm merkezi",Übersicht:"Genel bakış",Kunden:"Müşteriler",Angebote:"Teklifler",Bestellungen:"Siparişler",Lieferanten:"Tedarikçiler",Bestand:"Stok",Lagerplätze:"Depo yerleri",Umlagerungen:"Transferler",Inventur:"Envanter",Qualitätsprüfung:"Kalite kontrol",Freigaben:"Onaylar",Aufträge:"İş emirleri",Versand:"Sevkiyat",Lieferscheine:"İrsaliyeler",Dokumente:"Belgeler",Dateien:"Dosyalar",Besprechungen:"Toplantılar",Speichern:"Kaydet",Senden:"Gönder",Antworten:"Yanıtla",Abbrechen:"İptal",Löschen:"Sil",Bearbeiten:"Düzenle",Suchen:"Ara",Aktualisieren:"Yenile",Zurück:"Geri",Weiter:"İleri",Schließen:"Kapat",Offen:"Açık",Abgeschlossen:"Tamamlandı",Storniert:"İptal edildi",Gesamt:"Toplam",Datum:"Tarih",Beschreibung:"Açıklama",Menge:"Miktar",Artikel:"Ürün",Artikelnummer:"Ürün numarası",Lieferant:"Tedarikçi",Bestellung:"Sipariş","Keine Daten vorhanden":"Veri bulunmuyor","Wird geladen...":"Yükleniyor..." };

const IT: Woerterbuch = { ...EN, Unternehmen:"Azienda",Prozesse:"Processi",Zusammenarbeit:"Collaborazione",Einstellungen:"Impostazioni",Abmelden:"Disconnetti","Feierabend / NOVA schließen":"Termina lavoro / Chiudi NOVA","NOVA durchsuchen …":"Cerca in NOVA …",Zentrale:"Ufficio centrale",Vertrieb:"Vendite",Disposition:"Pianificazione",Buchhaltung:"Contabilità","CAD-Büro":"Ufficio CAD",Einkauf:"Acquisti",Lager:"Magazzino",Konfektion:"Confezione",Logistik:"Logistica",Kommunikation:"Comunicazione",Organisation:"Organizzazione",Mitarbeiter:"Dipendenti",Benutzerverwaltung:"Gestione utenti",Integrationen:"Integrazioni",Sicherheit:"Sicurezza",Alarmcenter:"Centro allarmi",Übersicht:"Panoramica",Kunden:"Clienti",Angebote:"Offerte",Bestellungen:"Ordini",Lieferanten:"Fornitori",Bestand:"Inventario",Lagerplätze:"Ubicazioni",Umlagerungen:"Trasferimenti",Inventur:"Inventario fisico",Qualitätsprüfung:"Controllo qualità",Prüfaufträge:"Ordini di ispezione",Freigaben:"Approvazioni",Sperrbestand:"Stock bloccato",Aufträge:"Ordini",Kommissionierung:"Prelievo",Ladungen:"Carichi",Versand:"Spedizione",Lieferscheine:"Documenti di consegna",Dokumente:"Documenti",Dateien:"File",Besprechungen:"Riunioni",Urlaubsplanung:"Pianificazione ferie",Speichern:"Salva",Senden:"Invia",Antworten:"Rispondi",Abbrechen:"Annulla",Löschen:"Elimina",Bearbeiten:"Modifica",Suchen:"Cerca",Aktualisieren:"Aggiorna",Zurück:"Indietro",Weiter:"Avanti",Schließen:"Chiudi",Offen:"Aperto",Abgeschlossen:"Completato",Storniert:"Annullato",Gesamt:"Totale",Datum:"Data",Beschreibung:"Descrizione",Menge:"Quantità",Artikel:"Articolo",Artikelnummer:"Codice articolo",Lieferant:"Fornitore",Bestellung:"Ordine","Keine Daten vorhanden":"Nessun dato disponibile","Wird geladen...":"Caricamento..." };

const RU: Woerterbuch = { ...EN, Unternehmen:"Компания",Prozesse:"Процессы",Zusammenarbeit:"Совместная работа",Einstellungen:"Настройки",Abmelden:"Выйти","Feierabend / NOVA schließen":"Завершить работу / Закрыть NOVA","NOVA durchsuchen …":"Поиск в NOVA …",Zentrale:"Центральный офис",Vertrieb:"Продажи",Disposition:"Планирование",Buchhaltung:"Бухгалтерия","CAD-Büro":"Отдел САПР",Einkauf:"Закупки",Lager:"Склад",Konfektion:"Комплектация",Logistik:"Логистика",Kommunikation:"Связь",Organisation:"Организация",Mitarbeiter:"Сотрудники",Benutzerverwaltung:"Управление пользователями",Integrationen:"Интеграции",Sicherheit:"Безопасность",Alarmcenter:"Центр оповещений",Übersicht:"Обзор",Kunden:"Клиенты",Angebote:"Предложения",Bestellungen:"Заказы",Lieferanten:"Поставщики",Bestand:"Запасы",Lagerplätze:"Места хранения",Umlagerungen:"Перемещения",Inventur:"Инвентаризация",Qualitätsprüfung:"Контроль качества",Prüfaufträge:"Задания на проверку",Freigaben:"Разрешения",Sperrbestand:"Заблокированный запас",Aufträge:"Заказы",Kommissionierung:"Комплектация",Ladungen:"Грузы",Versand:"Отгрузка",Lieferscheine:"Накладные",Dokumente:"Документы",Dateien:"Файлы",Besprechungen:"Совещания",Urlaubsplanung:"Планирование отпусков",Speichern:"Сохранить",Senden:"Отправить",Antworten:"Ответить",Abbrechen:"Отмена",Löschen:"Удалить",Bearbeiten:"Изменить",Suchen:"Поиск",Aktualisieren:"Обновить",Zurück:"Назад",Weiter:"Далее",Schließen:"Закрыть",Offen:"Открыто",Abgeschlossen:"Завершено",Storniert:"Отменено",Gesamt:"Всего",Datum:"Дата",Beschreibung:"Описание",Menge:"Количество",Artikel:"Товар",Artikelnummer:"Артикул",Lieferant:"Поставщик",Bestellung:"Заказ","Keine Daten vorhanden":"Нет данных","Wird geladen...":"Загрузка..." };

export function systemText(region: SpracheRegion, deutsch: string): string {
  if (region === "de-DE") return deutsch;
  const dict = region === "es-ES" ? ES : region === "tr-TR" ? TR : region === "it-IT" ? IT : region === "ru-RU" ? RU : EN;
  return dict[deutsch] ?? deutsch;
}
