"use client";

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { Download, FilePlus2, Filter, Plus, Save, Sheet, Trash2, Upload } from "lucide-react";

type Zellen = Record<string, string>;
type Blatt = { id: string; name: string; zellen: Zellen };
type Arbeitsmappe = { name: string; blaetter: Blatt[]; aktualisiertAm: string };

const SPALTEN = 12, ZEILEN = 60, SPEICHER = "nova-sheets-arbeitsmappe-v1";
const startMappe: Arbeitsmappe = { name: "Neue Arbeitsmappe", aktualisiertAm: new Date().toISOString(), blaetter: [{ id: "blatt-1", name: "Tabelle 1", zellen: { A1: "NOVA Sheets", A3: "Artikel", B3: "Menge", C3: "Preis", D3: "Gesamt", D4: "=B4*C4" } }] };

function spalte(i:number){return String.fromCharCode(65+i)}
function zahl(w:string){const n=Number(w.replace(",","."));return Number.isFinite(n)?n:0}
function formelWert(formel:string,zellen:Zellen,besucht=new Set<string>()):string{
  if(!formel.startsWith("="))return formel;
  let ausdruck=formel.slice(1).toUpperCase().replace(/(SUMME|SUM)\(([A-Z]\d+):([A-Z]\d+)\)/g,(_m,_f,von,bis)=>{const s1=von.charCodeAt(0)-65,s2=bis.charCodeAt(0)-65,z1=Number(von.slice(1)),z2=Number(bis.slice(1));let summe=0;for(let z=Math.min(z1,z2);z<=Math.max(z1,z2);z++)for(let s=Math.min(s1,s2);s<=Math.max(s1,s2);s++)summe+=zahl(formelWert(zellen[`${spalte(s)}${z}`]??"",zellen,besucht));return String(summe)});
  ausdruck=ausdruck.replace(/([A-Z]\d+)/g,(a)=>{if(besucht.has(a))return"0";const neu=new Set(besucht);neu.add(a);return String(zahl(formelWert(zellen[a]??"",zellen,neu)))});
  if(!/^[\d+\-*/().\s]+$/.test(ausdruck))return"#FORMEL?";
  try{const teile=ausdruck.match(/\d+(?:\.\d+)?|[()+\-*/]/g)??[],werte:number[]=[],ops:string[]=[];const rang:Record<string,number>={"+":1,"-":1,"*":2,"/":2};const rechne=()=>{const b=werte.pop()??0,a=werte.pop()??0,o=ops.pop();werte.push(o==="+"?a+b:o==="-"?a-b:o==="*"?a*b:b===0?0:a/b)};for(const t of teile){if(!Number.isNaN(Number(t)))werte.push(Number(t));else if(t==="(")ops.push(t);else if(t===")"){while(ops.at(-1)!=="("&&ops.length)rechne();ops.pop()}else{while(ops.at(-1)!=="("&&(rang[ops.at(-1)??""]??0)>=rang[t])rechne();ops.push(t)}}while(ops.length)rechne();const e=werte[0];return Number.isFinite(e)?String(Math.round(e*100)/100):"#FEHLER"}catch{return"#FORMEL?"}
}

export default function NovaSheets(){
  const[mappe,setMappe]=useState<Arbeitsmappe>(startMappe),[aktivId,setAktivId]=useState("blatt-1"),[auswahl,setAuswahl]=useState("A1"),[filter,setFilter]=useState(""),[meldung,setMeldung]=useState(""),[geladen,setGeladen]=useState(false);const datei=useRef<HTMLInputElement>(null);const mappeRef=useRef(mappe);
  useEffect(()=>{const g=localStorage.getItem(SPEICHER);if(g)try{const m=JSON.parse(g) as Arbeitsmappe;if(m.blaetter?.length){setMappe(m);setAktivId(m.blaetter[0].id)}}catch{}setGeladen(true)},[]);
  useEffect(()=>{mappeRef.current=mappe;if(geladen)localStorage.setItem(SPEICHER,JSON.stringify(mappe))},[mappe,geladen]);
  const blatt=mappe.blaetter.find(b=>b.id===aktivId)??mappe.blaetter[0];
  const zeilen=useMemo(()=>Array.from({length:ZEILEN},(_,i)=>i+1).filter(z=>!filter||Array.from({length:SPALTEN},(_,s)=>formelWert(blatt?.zellen[`${spalte(s)}${z}`]??"",blatt?.zellen??{}).toLowerCase()).some(v=>v.includes(filter.toLowerCase()))),[blatt,filter]);
  function setzen(a:string,w:string){setMappe(m=>({...m,aktualisiertAm:new Date().toISOString(),blaetter:m.blaetter.map(b=>b.id===aktivId?{...b,zellen:{...b.zellen,[a]:w}}:b)}))}
  function speichern(){localStorage.setItem(SPEICHER,JSON.stringify(mappe));setMeldung("Arbeitsmappe gespeichert.");setTimeout(()=>setMeldung(""),2200)}
  function neu(){const id=`blatt-${Date.now()}`;setMappe(m=>({...m,blaetter:[...m.blaetter,{id,name:`Tabelle ${m.blaetter.length+1}`,zellen:{}}]}));setAktivId(id)}
  function loeschen(id:string){if(mappe.blaetter.length===1){setMeldung("Mindestens ein Tabellenblatt muss bestehen bleiben.");setTimeout(()=>setMeldung(""),2500);return}const ziel=mappe.blaetter.find(b=>b.id===id);if(!ziel||!confirm(`Tabellenblatt „${ziel.name}“ wirklich löschen?`))return;setMappe(m=>{const blaetter=m.blaetter.filter(b=>b.id!==id);if(id===aktivId)setAktivId(blaetter[0].id);return{...m,blaetter,aktualisiertAm:new Date().toISOString()}})}
  async function exportieren(){const XLSX=await import("xlsx"),aktuell=mappeRef.current,wb=XLSX.utils.book_new();for(const b of aktuell.blaetter){const d=Array.from({length:ZEILEN},(_,z)=>Array.from({length:SPALTEN},(_,s)=>{const roh=b.zellen[`${spalte(s)}${z+1}`]??"";return roh.startsWith("=")?formelWert(roh,b.zellen):roh})),ws=XLSX.utils.aoa_to_sheet(d);for(const[a,roh]of Object.entries(b.zellen)){if(roh.startsWith("=")){const wert=Number(formelWert(roh,b.zellen));ws[a]={t:"n",f:roh.slice(1),v:Number.isFinite(wert)?wert:0}}}XLSX.utils.book_append_sheet(wb,ws,b.name.slice(0,31))}XLSX.writeFile(wb,`${aktuell.name.replace(/[^a-z0-9_-]/gi,"_")}.xlsx`);setMeldung("Aktuelle Arbeitsmappe wurde vollständig exportiert.");setTimeout(()=>setMeldung(""),2500)}
  async function importieren(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const XLSX=await import("xlsx"),wb=XLSX.read(await f.arrayBuffer());const blaetter=wb.SheetNames.map((name,i)=>{const rows=XLSX.utils.sheet_to_json<(string|number)[]>(wb.Sheets[name],{header:1,raw:false}),zellen:Zellen={};rows.slice(0,ZEILEN).forEach((r,z)=>r.slice(0,SPALTEN).forEach((v,s)=>{if(v!==undefined&&v!=="")zellen[`${spalte(s)}${z+1}`]=String(v)}));return{id:`blatt-${Date.now()}-${i}`,name,zellen}});if(blaetter.length){setMappe({name:f.name.replace(/\.xlsx?$/i,""),blaetter,aktualisiertAm:new Date().toISOString()});setAktivId(blaetter[0].id)}}
  async function bestand(){const r=await fetch("/api/artikel",{cache:"no-store"}),j=await r.json();if(!r.ok){setMeldung(j.fehler??"Bestand konnte nicht geladen werden.");return}const artikel:Record<string,unknown>[]=Array.isArray(j)?j:(j.artikel??[]),zellen:Zellen={A1:"Artikelnummer",B1:"Produktname",C1:"Größe",D1:"Variante",E1:"Bestand",F1:"Reserviert",G1:"Verfügbar"};artikel.slice(0,ZEILEN-1).forEach((a,i)=>{const z=i+2;[a.artikelnummer,a.produktname,a.groesse,a.variante,a.bestand,a.reserviert,a.verfuegbar].forEach((v,s)=>zellen[`${spalte(s)}${z}`]=String(v??""))});setMappe(m=>({...m,blaetter:m.blaetter.map(b=>b.id===aktivId?{...b,name:"ERP Bestand",zellen}:b)}));setMeldung(`${Math.min(artikel.length,ZEILEN-1)} Artikel übernommen.`)}
  if(!blatt)return null;
  return <main className="min-h-screen bg-[var(--nova-hintergrund)] p-8 pl-28 text-[var(--nova-text)]"><div className="mx-auto max-w-[1600px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.24em] text-[var(--nova-akzent)]">NOVA Office</p><h1 className="mt-1 flex items-center gap-3 text-4xl font-bold"><Sheet/> NOVA Sheets</h1><input value={mappe.name} onChange={e=>setMappe({...mappe,name:e.target.value})} className="mt-2 border-0 bg-transparent text-[var(--nova-text-schwaecher)] outline-none"/></div><div className="flex flex-wrap gap-2"><button onClick={neu} className={knopf}><FilePlus2 size={17}/>Neues Blatt</button><button onClick={()=>datei.current?.click()} className={knopf}><Upload size={17}/>Excel öffnen</button><button onClick={()=>void exportieren()} className={knopf}><Download size={17}/>Export</button><button onClick={()=>void bestand()} className={primaer}>ERP-Bestand einfügen</button><button onClick={speichern} className={primaer}><Save size={17}/>Speichern</button><input ref={datei} hidden type="file" accept=".xlsx,.xls" onChange={e=>void importieren(e)}/></div></div>{meldung&&<p className="mt-4 rounded-xl border border-[var(--nova-akzent)] bg-[var(--nova-akzent-transparent)] px-4 py-3">{meldung}</p>}
  <section className="mt-6 overflow-hidden rounded-2xl border border-[var(--nova-rand)] bg-[var(--nova-flaeche)] shadow-xl"><div className="flex items-center gap-3 border-b border-[var(--nova-rand)] p-3"><span className="w-16 rounded-lg bg-[var(--nova-hintergrund)] px-3 py-2 text-center font-mono">{auswahl}</span><b>fx</b><input value={blatt.zellen[auswahl]??""} onChange={e=>setzen(auswahl,e.target.value)} className="min-w-0 flex-1 rounded-lg border border-[var(--nova-rand)] bg-[var(--nova-hintergrund)] px-3 py-2 outline-none focus:border-[var(--nova-akzent)]"/><div className="relative"><Filter className="pointer-events-none absolute left-3 top-2.5" size={16}/><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Zeilen filtern" className="w-48 rounded-lg border border-[var(--nova-rand)] bg-[var(--nova-hintergrund)] py-2 pl-9 pr-3 outline-none"/></div></div><div className="max-h-[65vh] overflow-auto"><table className="border-collapse text-sm"><thead className="sticky top-0 z-10"><tr><th className={kopf}>#</th>{Array.from({length:SPALTEN},(_,s)=><th key={s} className={`${kopf} min-w-40`}>{spalte(s)}</th>)}</tr></thead><tbody>{zeilen.map(z=><tr key={z}><th className={`${kopf} sticky left-0`}>{z}</th>{Array.from({length:SPALTEN},(_,s)=>{const a=`${spalte(s)}${z}`,roh=blatt.zellen[a]??"";return <td key={a} className={`border border-[var(--nova-rand)] p-0 ${auswahl===a?"outline-2 outline-[var(--nova-akzent)] outline-offset-[-2px]":""}`}><input aria-label={a} value={roh.startsWith("=")?formelWert(roh,blatt.zellen):roh} onFocus={()=>setAuswahl(a)} onChange={e=>setzen(a,e.target.value)} className="h-9 w-full bg-transparent px-2 outline-none"/></td>})}</tr>)}</tbody></table></div><div className="flex items-center gap-2 overflow-x-auto border-t border-[var(--nova-rand)] p-2">{mappe.blaetter.map(b=><div key={b.id} className={`flex shrink-0 items-center rounded-lg ${b.id===aktivId?"bg-[var(--nova-akzent)] text-white":"hover:bg-[var(--nova-flaeche-hover)]"}`}><button onClick={()=>setAktivId(b.id)} onDoubleClick={()=>{const n=prompt("Name des Tabellenblatts",b.name);if(n)setMappe(m=>({...m,blaetter:m.blaetter.map(x=>x.id===b.id?{...x,name:n}:x)}))}} className="px-4 py-2">{b.name}</button><button onClick={()=>loeschen(b.id)} title={`${b.name} löschen`} className="mr-1 rounded-md p-1.5 opacity-60 transition hover:bg-black/15 hover:opacity-100"><Trash2 size={14}/></button></div>)}<button onClick={neu} title="Neues Blatt" className="shrink-0 rounded-lg p-2 hover:bg-[var(--nova-flaeche-hover)]"><Plus size={18}/></button></div></section><p className="mt-3 text-xs text-[var(--nova-text-schwaecher)]">Änderungen werden automatisch gespeichert · Formeln: =B4*C4, =A1+B1 oder =SUMME(A1:A10) · Doppelklick zum Umbenennen · Papierkorb zum Löschen.</p></div></main>
}

const knopf="flex items-center gap-2 rounded-xl border border-[var(--nova-rand)] bg-[var(--nova-flaeche)] px-4 py-3 font-semibold hover:border-[var(--nova-akzent)]";
const primaer="flex items-center gap-2 rounded-xl bg-[var(--nova-akzent)] px-4 py-3 font-semibold text-white hover:brightness-110";
const kopf="border border-[var(--nova-rand)] bg-[var(--nova-hintergrund)] px-3 py-2 text-[var(--nova-text-schwaecher)]";
